In [ ]:
import numpy as np
from scipy.linalg import block_diag

In [ ]:
Mat1=block_diag(np.ones((2,2)),np.zeros((2,2)),3,(4*np.ones((2,2))-2*np.eye(2)))

In [ ]:
Mat1.shape

(7, 7)

In [ ]:
Mat1.reshape((1,49))

array([[1., 1., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        3., 0., 0., 0., 0., 0., 0., 0., 2., 4., 0., 0., 0., 0., 0., 4.,
        2.]])

In [ ]:
tab=np.array([[1,2,3],[4,5,6]])
tab

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
tab.reshape((3,2))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
tab.reshape((1,6))

array([[1, 2, 3, 4, 5, 6]])

In [ ]:
tab.reshape(-1)

array([1, 2, 3, 4, 5, 6])

SyntaxError: ignored

### Zadanie 7
Utwórz tablicę

$$
\begin{bmatrix}
1&2&3&4\\
5&6&7&8 \\
9&10&11&12\\
13&14&15&16
\end{bmatrix}
$$

In [ ]:
np.arange(1,17).reshape((4,4))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

#### Zadanie
Utwórz macierz (indeksy od 1) o wymiarach $5x6x3$ i elementach

$$
X[i,j,k]=100+60(i-1)+10(j-1)+300(k-1)
$$

In [ ]:
a1=np.arange(1,5).reshape((2,2))
a2=np.arange(1,9).reshape((2,4))

In [ ]:
a1+a2

ValueError: ignored

In [ ]:
2*np.eye(2)*np.ones((2,2))

array([[2., 0.],
       [0., 2.]])

In [ ]:
np.sin(a1)

array([[ 0.84147098,  0.90929743],
       [ 0.14112001, -0.7568025 ]])

In [ ]:
A=np.arange(1,17).reshape((2,8))
A

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16]])

In [ ]:
A.T

array([[ 1,  9],
       [ 2, 10],
       [ 3, 11],
       [ 4, 12],
       [ 5, 13],
       [ 6, 14],
       [ 7, 15],
       [ 8, 16]])

In [ ]:
B=np.arange(1,17)
B

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [ ]:
B.T

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

## Agregacja

In [ ]:
A

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16]])

## Funkcje agregujące
* ```np.mean``` - średnia
* ```np.std``` - odchylenie standardowe
* ```np.var``` - wariancja $var=std^2$
* ```np.median```
* ```np.sum```
* ```np.prod```
* ```np.cumsum``` - skumulowana suma
* ```np.cumprod```
* ```np.min, np.max```
* ```np.argmin, np.argmax```
* ```np.all, np.any``` - sprawdza czy wszystkie lub którykolwiek są True (np. różne od zera)

In [ ]:
np.mean(A,axis=1)

array([ 4.5, 12.5])

In [ ]:
L=np.random.random(100)
L

array([0.9639754 , 0.97760667, 0.36402848, 0.21839119, 0.52982466,
       0.38012446, 0.32917765, 0.42285803, 0.35210716, 0.23909486,
       0.65813255, 0.47066459, 0.47831099, 0.99144909, 0.28868027,
       0.48520932, 0.09906172, 0.79052803, 0.68150679, 0.79896194,
       0.47217372, 0.83520475, 0.25420224, 0.75207267, 0.27055714,
       0.68593344, 0.75437774, 0.7875034 , 0.17313591, 0.84746015,
       0.93792352, 0.4506617 , 0.29568043, 0.94800015, 0.18352828,
       0.38913536, 0.17755459, 0.22650966, 0.28093882, 0.51304656,
       0.48772011, 0.47308683, 0.01951505, 0.91931361, 0.85263599,
       0.64633579, 0.93413881, 0.8315568 , 0.97525457, 0.19860497,
       0.31383569, 0.0170194 , 0.04248141, 0.74126495, 0.33950596,
       0.19459508, 0.48383571, 0.96379564, 0.31024517, 0.47061674,
       0.44469186, 0.03773189, 0.7387245 , 0.13715442, 0.18519965,
       0.51061193, 0.60048051, 0.20243176, 0.42817166, 0.10155204,
       0.46977285, 0.66230594, 0.44502282, 0.58861849, 0.68761

In [ ]:
np.cumsum(A,axis=1)

array([[  1,   3,   6,  10,  15,  21,  28,  36],
       [  9,  19,  30,  42,  55,  69,  84, 100]])

In [ ]:
A*(A>5)

array([[ 0,  0,  0,  0,  0,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16]])

In [ ]:
A[A>5]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [ ]:
if np.all(A>5):
  print('tak')

In [ ]:
L=np.arange(1,17).reshape(4,4)
L

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
x=np.array([1,2,3,4])
y=np.array([0,4,1,6])

In [ ]:
x<y

array([False,  True, False,  True])

In [ ]:
L[x<y]

array([[ 5,  6,  7,  8],
       [13, 14, 15, 16]])

#### Zadanie (rozwiązujemy na końcu pliku)

1. Wygeneruj losową tablicę L(100x10) liczb całkowitych z przedziału [0,10] generatorem=12345 (```np.random.seed(12345)``` przed użyciem ```np.random.random_integers```. Sprawdź:
* ile jest w niej liczb większych od 3
* jaka jest średnia w każdej kolumnie
* określ w których wierszach co najmniej połowa liczb jest $\geq 5$
* wypisz kolejno (wierszami) wsyzsktie elementy tablicy z przedziału [2,5].
* stwórz nową talibcę, zerując w L wszysktie elementy spoza przedziału [2,5].
* znajdź wiersze, które nie zawierają żadnego zera

Zobacz także

* ```np.where```
* ```np.choose```
* ```np.select```
* ```np.nonzero```

## Algebra liniowa w Pythonie
* ```np.linalg.inv ``` - odwrotność macierzy
* ```np.linalg.det``` - wyznacznik
* ```np.linalg.eig``` - wartości i wektory własne
* ```np.dot``` - iloczyn macierzowy
* ```np.inner``` - iloczyn skalarny
* ```np.cross``` - iloczyn wektorowy

* ```np.linalg.norm``` - norma macierzy lub wektora


In [ ]:
np.linalg.inv

#### Zadanie
Niech $A=\begin{bmatrix} 2&3\\0&2\end{bmatrix}$ oraz $B=\begin{bmatrix} 2 & 5 \\ 3 & 8 \end{bmatrix}$. Wyznacz iloczyn $C=BAB^{-1}$. Oblicz wartości własne macierzy $A$ i macierzy $C$.

In [ ]:
A=np.array([[2,3],[0,2]])
B=np.array([[2,5],[3,8]])
C=np.dot(B,np.dot(A,np.linalg.inv(B)))

In [ ]:
np.linalg.eig(A)[0]

array([2., 2.])

In [ ]:
np.linalg.eig(A)[1][:,0]

array([1., 0.])

In [ ]:
np.linalg.eig(C)[0]

array([2.+1.97405238e-07j, 2.-1.97405238e-07j])

#### Zadanie

1. Wygeneruj losową tablicę L(100x10) liczb całkowitych z przedziału [0,10] generatorem=12345 (```np.random.seed(12345)``` przed użyciem ```np.random.random_integers```. Sprawdź:
* ile jest w niej liczb większych od 3
* jaka jest średnia w każdej kolumnie
* określ w których wierszach co najmniej połowa liczb jest $\geq 5$
* wypisz kolejno (wierszami) wsyzsktie elementy tablicy z przedziału [2,5].
* stwórz nową talibcę, zerując w L wszysktie elementy spoza przedziału [2,5].
* znajdź wiersze, które nie zawierają żadnego zera

In [ ]:
np.random.seed(12345)
L=np.random.random_integers(low=0, high=10, size=(100,10))
print(L)

In [ ]:
#ile jest w niej liczb większych od 3
np.sum(L>3)

In [ ]:
#jaka jest średnia w każdej kolumnie
np.mean(L,axis=0)

In [ ]:
#określ w których wierszach co najmniej połowa liczb jest ≥5
L1=L>=5
L2=np.sum(L1,axis=1)
np.where(L2>=5)
#kolumny numerowane od 0

In [ ]:
L3=L<=5
L4=L>=2
L5=L3==L4
#stwórz nową talibcę, zerując w L wszysktie elementy spoza przedziału [2,5]
L6 = np.where(L5==True, L, 0)

In [ ]:
#znajdź wiersze, które nie zawierają żadnego zera
for i in range (100):
    if np.all(L5[i]<0):
        print(i)