# Algebra liniowa

In [ ]:
import numpy as np
L=np.random.randint(low=0, high=10, size=(5,5))
L


array([[6, 7, 2, 7, 3],
       [5, 2, 1, 1, 5],
       [4, 3, 5, 3, 3],
       [2, 0, 8, 4, 5],
       [0, 7, 5, 8, 8]])

In [ ]:
%timeit(np.linalg.eig(L))

The slowest run took 20.62 times longer than the fastest. This could mean that an intermediate result is being cached.
10000 loops, best of 5: 32.1 µs per loop


In [ ]:
M=np.linalg.eig(L)
np.max(M[0])

(20.927316989873255+0j)

In [ ]:
A=np.array([[1,0],[0,2]])
B=np.array([[1,7],[4,9]])
np.linalg.det(B)
np.dot(B,np.dot(np.diag([1,7]),np.linalg.inv(B)))

B@B

array([[ 29,  70],
       [ 40, 109]])

# Rozkłady macierzy

In [ ]:
SVD = np.linalg.svd(L)
SVD[0] @ np.diag(SVD[1]) @ SVD[2]

array([[ 6.00000000e+00,  7.00000000e+00,  2.00000000e+00,
         7.00000000e+00,  3.00000000e+00],
       [ 5.00000000e+00,  2.00000000e+00,  1.00000000e+00,
         1.00000000e+00,  5.00000000e+00],
       [ 4.00000000e+00,  3.00000000e+00,  5.00000000e+00,
         3.00000000e+00,  3.00000000e+00],
       [ 2.00000000e+00, -5.74631134e-15,  8.00000000e+00,
         4.00000000e+00,  5.00000000e+00],
       [ 1.69339567e-15,  7.00000000e+00,  5.00000000e+00,
         8.00000000e+00,  8.00000000e+00]])

In [ ]:
(SVD [0] @ SVD [0].T).round(0)

array([[ 1., -0.,  0., -0.,  0.],
       [-0.,  1.,  0.,  0., -0.],
       [ 0.,  0.,  1., -0., -0.],
       [-0.,  0., -0.,  1., -0.],
       [ 0., -0., -0., -0.,  1.]])

In [ ]:
Mat = np.array([[1,2,3],[1,2,1],[0,1,0]])
np.linalg.eig(Mat)
np.linalg.svd(Mat)

(array([[-0.8384388 , -0.50673863, -0.20058996],
        [-0.52438113,  0.6498237 ,  0.55023049],
        [-0.14847494,  0.56652018, -0.81056158]]),
 array([4.39972444, 1.22684012, 0.37052417]),
 array([[-0.3097512 , -0.65324882, -0.69088362],
        [ 0.11662894,  0.69502969, -0.70945854],
        [ 0.94363758, -0.30033266, -0.13909856]]))

In [ ]:
Mat1=Mat[1:3]
Mat1

array([[1, 2, 1],
       [0, 1, 0]])

In [ ]:
Mat_SVD = np.linalg.svd(Mat1)
sigma = np.diag(Mat_SVD[1])
Mat2 = np.concatenate([Mat1, Mat1], axis=1)
sigma2 = np.concatenate([sigma,np.zeros((2,1))], axis=1)
Mat_SVD[0] @ sigma2 @ Mat_SVD[2]

array([[1.00000000e+00, 2.00000000e+00, 1.00000000e+00],
       [3.60336759e-16, 1.00000000e+00, 1.33129905e-16]])

# Potegowanie

In [ ]:
np.linalg.matrix_power(Mat, 20)

The slowest run took 10.10 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 5: 8.43 µs per loop


In [ ]:
Mat_rozklad= np.linalg.eig(Mat)
JA= np.diag(Mat_rozklad[0])
P=Mat_rozklad[1]
Mat3= (P @ np.linalg.matrix_power(JA, 20) @ np.linalg.inv(P)).round(0)

# Rozwiązywanie układów równań

In [ ]:
np.linalg.cond(Mat)

In [ ]:
A = np.array([[1,0,2],[3,2,1],[1,1,1]])
b1 = np.array([20.001, -9.999, 100.00001])
b2 = np.array([20, -10, 100])
np.linalg.solve(A, b1)

array([-133.33234667,  156.66568333,   76.66667333])